#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  block compile virtualenv
  mkdir -p "$shome/bin"
  ln -nfs ../vendor/virtualenv/bin/pip "$shome/bin/pip36"
  ln -nfs ../vendor/virtualenv/bin/virtualenv "$shome/bin/virtualenv36"
  ln -nfs ../vendor/virtualenv/bin/pipenv "$shome/bin/pipenv36"
}

main "$@"
