#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source normalize

  local pth_requirements="$(realpath "$1")"; shift

  cd "$shome"
  "$shome/vendor/virtualenv/bin/pip" install --upgrade -r <(cat "$pth_requirements" | cut -d= -f1)
  "$shome/vendor/virtualenv/bin/pip" freeze | tee "$pth_requirements"
}

main "$@"
