#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_py36="0.0.1"
  jq -n --arg py36 "$ver_py36" '{py36: $py36}'
}

version "$@"
