#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_pipenv36="$(pipenv36 --version 2>/dev/null | awk '{print $3}' || true)"
  jq -n --arg py36 "$ver_py36" '{py36: $py36}'
}

version "$@"
